# Generated by Django 3.0.7 on 2020-07-03 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_auto_20200701_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('landmark', models.CharField(max_length=200)),
                ('alternative_no', models.IntegerField()),
                ('default', models.BooleanField(default=False)),
                ('address_type', models.CharField(choices=[('W', 'WORK'), ('H', 'HOME')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Address'),
        ),
    ]
